---
title: "Stock Price Analysis"
output: word_document
authors: "Jianan Ou, Ramasamy Mohan, Atit Kalpesh Kothari, Priya Gopalakrishnan, Subhramanyam Mudundi"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stock Price Analysis

# Dataset:

```{r cars}
# Use getSymbol to grab data from yahoo finance by mentioning the start and end date
getSymbols("AAPL", src = 'yahoo', from = "2000-01-31", to = "2019-12-31", auto.assign = TRUE, warnings = FALSE) 
summary(AAPL)

# We can then transform the daily data into weekly data using to.weekly()
prices_weekly <- to.weekly(AAPL, indexAt = "lastof", OHLC = FALSE)

# Data to begin, create a copy
dataset = AAPL
summary(dataset)

hist(dataset$AAPL.Close)
```

# Data screening:

```{r}
colnames(dataset) = c("open", "high", "low", "close", "volume", "adjusted")
K = 6
N = nrow(dataset)
model1 = lm(adjusted ~ . ,data=dataset)

## leverage cutoff
leverage = hatvalues(model1)
cutleverage = (2*K + 2) / N
badlaverage = as.numeric(leverage > cutleverage)
table(badlaverage)

## cook cutoff
cooks = cooks.distance(model1)
cutcook = 4 / (N-K-1)
badcooks = as.numeric(cooks > cutcook)
table(badcooks)

## remove outlier
total = badcooks + badlaverage
noout = subset(dataset, total < 1)
```

## Normality: 

```{r}
## Model 2 -- revised model after cleaning data
model2 = lm(adjusted ~ . ,data=noout)
summary(model2, correlation = TRUE)
fitted = scale(model2$fitted.values)
standardized2 = rstudent(fake)
hist(standardized2)
```

## Linearity:

```{r}
{qqnorm(standardized2)
abline(0,1)}
```

## Homogeneity/Homoscedasticity: 

```{r}
{plot(fitted, standardized2)
abline(0,0)
abline(v = 0)}
```

## Pearson Correlation Method: 

```{r}
cor.test(noout$adjusted,noout$volume,method = "pearson")
```

## Manual Step-Wise Regression:

```{r}
###Model 3 -- Model Selection
dat1 = noout

###Manuel Step-wise regression
null=lm(adjusted ~ 1, data=dat1)
StepF0=null
summary(StepF0)

add1(StepF0, scope = ~open + high + low + close + volume, test='F', data=dat1)
StepF1=update(StepF0, ~ low)
drop1(StepF1, test='F',data=dat1)

add1(StepF1, scope = ~open + high + low + close + volume, test='F', data=dat1)
StepF2=update(StepF1, ~ low + open)
summary(StepF2)
drop1(StepF2, test='F',data=dat1)

add1(StepF2, scope = ~open + high + low + close + volume, test='F', data=dat1)
StepF3=update(StepF2, ~ low + open + volume)
summary(StepF3)
drop1(StepF3, test='F',data=dat1)

add1(StepF3, scope = ~open + high + low + close + volume, test='F', data=dat1)

```

## Automatic Step-Wise Regression:

```{r}
### Model 4 -- Automatic Step-wise regression, to confirm Model 3
model4.full = ols(adjusted ~ open
                  + high + low + close + volume, data=dat1)
fastbw(model4.full, rule="p",sls=0.001)
```

## ANOVA

```{r}
aov_mod = aov(adjusted ~ open,data = noout)

summary(aov_mod) 

# Check anova assumptions:
plot(aov_mod,1)
plot(aov_mod,2)
plot(aov_mod,3)
plot(aov_mod,4)

```


```{r pressure, echo=FALSE}
plot(pressure)
```
